model: 
  type: NeuralNetwork
  in_features: 2
  out_features: 1
  n_neurons: 16
  n_layers: 4

underlier:
  type: BrownianStock
  mu: 0.2
  sigma: 0.3

# underlier:
#   type: HestonStock
#   mu: 0.05
#   kappa: 1.5
#   theta: 0.04
#   xi: 0.3
#   nu0: 0.04

derivative:
  type: LookbackOption
  short: true
  call: true
  strike: 1.1
  maturity: 0.4

training:
  n_paths: 5000
  n_epochs: 100
  lr: 0.01

loss:
  type: ExpectedShortfall
  p: 0.1



