model: 
  type: NeuralNetwork
  in_features: 2
  out_features: 1

underlier:
  type: BrownianStock
  mu: 0.2
  sigma: 0.3

derivative:
  type: EuropeanOption
  call: true
  strike: 1.1
  maturity: 0.4

training:
  n_paths: 500
  n_epochs: 100

